#!/usr/bin/env python
env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src"])
sources = Glob("src/*.cpp")
env["SHLIBPREFIX"] = ""
library = env.SharedLibrary(
    "bin/voxel_native{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
Default(library)
